# -*- coding: utf-8 -*-
"""HackBio StageZero.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iotWGZZbpUliC_k4JaZvBJB73ZoCSdKB

HACKBIO STAGEZERO PYTHON SCRIPT.py
"""

# Create a script with the names, slack usernme, affliations, hobby and DNA sequence of gene they love for Team Methionine
import pandas as pd
Team_Methionine = {
    "Names": ["Oluwadamilola Adeyemi", "Rajeefa Rasheed", "Oyedele Temitayo Victoria", "Chaya S Bangalore"],
    "Slack_username": ["Oluwadamilola Adeyemi", "Rajeefa", "Temitayo", "Chaya S Bangalore"],
    "1 Hobby": ["Watching movies", "Reading", "Poetry reading", "N/A"],
    "Dna": ["CGGCTCGTATGTTGTGTGGAATTGTGAGCGGATAACAATTTCACACAGGAAACAG", "AGGGAACCCCTTACCTGGAATCTGGAATCAGCCTCTTCTCTGATGACCCTGAATCTGATCCTTCTGAAGACAGAGCCCCAGAGTCAGCTCGTGTTGGCAACATACCATCTTCAACCTCTGCATTGAAAGTTCCCCAATTGAAAGTTGCAGAATCTGCCCAGAGTCCAGCTGCTGCTCATACTACTGATACTGCTGGGTATAATGCAATGGAAGAAAGTGTGAGCAGGGAGAAGCCAGAATTGACAGCTTCAACAGAAAGGGTCAACAAAAGAATGTCCATGGTGGTGTCTGGCCTGACCCCAGAAGAATTT", "aaccgacgcgcgtctgtggagaagcggcttggtcgggggtggtctcgtggggtcctgcctgtttagtcgctttcagggttcttgagccccttcacgaccgtcaccatggaagtgtcaccattgcagcctgtaaatgaaaatatgcaagtcaacaaaataaagaaaaatgaagatgctaagaaaagactgtctgttgaaagaatctatcaaaagaaaacacaattggaacatattttgctc", "N/A"]
}
df = pd.DataFrame(Team_Methionine)
print(df)

